// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADRiw4LdQ_8N7pa03fZLo4La31Sa_nlrk',
    appId: '1:170148598609:web:cc1f3c6b36623185cfb970',
    messagingSenderId: '170148598609',
    projectId: 'juegoactividad',
    authDomain: 'juegoactividad.firebaseapp.com',
    storageBucket: 'juegoactividad.appspot.com',
    measurementId: 'G-RZKLZK1D2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFQPj6JOEn4uGHFbnkItMiJXGXbm_qByg',
    appId: '1:170148598609:android:0b97e17bb1a76befcfb970',
    messagingSenderId: '170148598609',
    projectId: 'juegoactividad',
    storageBucket: 'juegoactividad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAJ9M3k2C4Ui2Jlz6oBDGln2MXl8ed3CQ',
    appId: '1:170148598609:ios:48919883aec1799bcfb970',
    messagingSenderId: '170148598609',
    projectId: 'juegoactividad',
    storageBucket: 'juegoactividad.appspot.com',
    iosClientId: '170148598609-eq9lnjbv45dgvaapvu6f3qih4esbl2e4.apps.googleusercontent.com',
    iosBundleId: 'com.Carlos.juegoActividad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAJ9M3k2C4Ui2Jlz6oBDGln2MXl8ed3CQ',
    appId: '1:170148598609:ios:48919883aec1799bcfb970',
    messagingSenderId: '170148598609',
    projectId: 'juegoactividad',
    storageBucket: 'juegoactividad.appspot.com',
    iosClientId: '170148598609-eq9lnjbv45dgvaapvu6f3qih4esbl2e4.apps.googleusercontent.com',
    iosBundleId: 'com.Carlos.juegoActividad',
  );
}
