// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZxtHmjU3P7Pb9t-YxukrTbotxdck-I-g',
    appId: '1:926967898105:web:06414cae470a7f4cf8a728',
    messagingSenderId: '926967898105',
    projectId: 'actividadinterfaces-75991',
    authDomain: 'actividadinterfaces-75991.firebaseapp.com',
    storageBucket: 'actividadinterfaces-75991.appspot.com',
    measurementId: 'G-L2WF4RCCSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDttVgHNPMaJnZTc1WirLKOkK8kHjR4zOM',
    appId: '1:926967898105:android:b669bdfc5da51cc7f8a728',
    messagingSenderId: '926967898105',
    projectId: 'actividadinterfaces-75991',
    storageBucket: 'actividadinterfaces-75991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsoMpwzb1GkzBWX622HiFwP-RioF-lL58',
    appId: '1:926967898105:ios:b3b3d55caf5f5163f8a728',
    messagingSenderId: '926967898105',
    projectId: 'actividadinterfaces-75991',
    storageBucket: 'actividadinterfaces-75991.appspot.com',
    iosClientId: '926967898105-6okket6rbe355m3rt96misj3m1qttqo9.apps.googleusercontent.com',
    iosBundleId: 'com.Carlos.juegoActividad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsoMpwzb1GkzBWX622HiFwP-RioF-lL58',
    appId: '1:926967898105:ios:b3b3d55caf5f5163f8a728',
    messagingSenderId: '926967898105',
    projectId: 'actividadinterfaces-75991',
    storageBucket: 'actividadinterfaces-75991.appspot.com',
    iosClientId: '926967898105-6okket6rbe355m3rt96misj3m1qttqo9.apps.googleusercontent.com',
    iosBundleId: 'com.Carlos.juegoActividad',
  );
}
